
POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IiIsImV4cCI6MTcxMzM4MzA4MSwidXNlcklEIjoiIn0.cWGNNkKx1KjQTrrCkQbjQvrwXb8ZbJ2JtOmHXNdiqYI

{
  "name": "Test event",
  "description" : "Test event description",
  "location": "A test location",
  "dateTime" : "2025-01-01T15:30:00.000Z"
}


